In [1]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np

In [2]:
test = pd.read_csv('BPI_Challenge_2012-test.csv', sep=',')
train = pd.read_csv('BPI_Challenge_2012-training.csv', sep=',')

In [3]:
train['event concept:name'] = pd.factorize(train['event concept:name'])[0]
train['event lifecycle:transition'] = pd.factorize(train['event lifecycle:transition'])[0]
test['event concept:name'] = pd.factorize(test['event concept:name'])[0]
test['event lifecycle:transition'] = pd.factorize(test['event lifecycle:transition'])[0]

In [4]:
train

eventID   case concept:name                  case REG_DATE  \
0                    0             173688  2011-10-01T00:38:44.546+02:00   
1                    1             173688  2011-10-01T00:38:44.546+02:00   
2                    2             173688  2011-10-01T00:38:44.546+02:00   
3                    3             173688  2011-10-01T00:38:44.546+02:00   
4           4294967296             173691  2011-10-01T08:08:58.256+02:00   
...                ...                ...                            ...   
214372  38835094290529             201854  2012-01-18T02:09:07.029+01:00   
214373  38835094290528             201854  2012-01-18T02:09:07.029+01:00   
214374  38835094290530             201854  2012-01-18T02:09:07.029+01:00   
214375  35858681954366             199678  2012-01-10T19:16:52.800+01:00   
214376  35858681954367             199678  2012-01-10T19:16:52.800+01:00   

        case AMOUNT_REQ  event concept:name  event lifecycle:transition  \
0                 20000                   0                           0   
1                 20000                   1                           0   
2                 20000                   2                           0   
3                 20000                   3                           1   
4                  5000                   0                           0   
...                 ...                 ...                         ...   
214372            50000                  12                           0   
214373            50000                  13                           0   
214374            50000                  17                           0   
214375            30000                  11                           2   
214376            30000                  11                           0   

           event time:timestamp  
0       01-10-2011 00:38:44.546  
1       01-10-2011 00:38:44.880  
2       01-10-2011 00:39:37.906  
3       01-10-2011 00:39:38.875  
4       01-10-2011 08:08:58.256  
...                         ...  
214372  14-03-2012 15:30:19.361  
214373  14-03-2012 15:30:19.361  
214374  14-03-2012 15:30:23.187  
214375  14-03-2012 15:36:15.299  
214376  14-03-2012 15:40:34.231  

[214377 rows x 7 columns]

In [5]:
print('Number of observations in the training data:', len(train))
print('Number of observations in the test data:',len(test))

Number of observations in the training data: 214377
Number of observations in the test data: 47823


In [6]:
features = train.columns[3:6]
features

Index(['case AMOUNT_REQ', 'event concept:name', 'event lifecycle:transition'], dtype='object')

In [7]:
y = pd.factorize(train['event concept:name'])[0]
y

array([ 0,  1,  2, ..., 17, 11, 11], dtype=int64)

In [8]:
clf = RandomForestClassifier(n_jobs=2, random_state=0)
clf.fit(train[features], y)

RandomForestClassifier(n_jobs=2, random_state=0)

In [9]:
clf.predict(test[features])

array([ 0,  1,  2, ..., 11, 17, 17], dtype=int64)

In [10]:
clf.predict_proba(test[features])[0:10]

array([[1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  ],
       [0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       

In [11]:
preds = clf.predict(test[features])

In [12]:
preds[0:5]

array([0, 1, 2, 0, 1], dtype=int64)

In [13]:
test['event concept:name'].head()

0    0
1    1
2    2
3    0
4    1
Name: event concept:name, dtype: int64

In [16]:
pd.crosstab(test['event concept:name'], preds, rownames=['Actual Species'], colnames=['Predicted Species'])

Predicted Species    0     1     2     3     4     5     6     7    8     9   \
Actual Species                                                                 
0                  2618     0     0     0     0     0     0     0    0     0   
1                     0  2618     0     0     0     0     0     0    0     0   
2                     0     0  1483     0     0     0     0     0    0     0   
3                     0     0     0  1483     0     0     0     0    0     0   
4                     0     0     0   190  4961  6219     0     0    0     0   
5                     0     0     0     0     0  2904     0     0    0     0   
6                     0     0     0     0     0     0  1014     0    0     0   
7                     0     0     0     0     0     0     0  1344    0     0   
8                     0     0     0     0     0     0     0     0  991     0   
9                     0     0     0     0     0     0     0     0    0  1344   
10                    0     0     0     0     0     0     0     0    0     0   
11                    0     0     0     0     0     0     0     0    0     0   
12                    0     0     0     0     0     0     0     0    0     0   
13                    0     0     0     0     0     0     0     0    0     0   
14                    0     0     0     0     0     0     0     0    0     0   
15                    0     0     0     0     0     0     0     0    0     0   
16                    0     0     0     0     0     0     0     0    0     0   
17                    0     0     0     0     0     0     0     0    0     0   
18                    0     0     0     0     0     0     0     0    0     0   
19                    0     0     0     0     0     0     0     0    0     0   
20                    0     0     0     0     0     0     0     0    0     0   
21                    0     0     0     0     0     0     0     0    0     0   
22                    0     0     0     0     0     0     0     0    0     0   

Predicted Species  ...   13   14   15    16    17   18   19   20   21   22  
Actual Species     ...                                                      
0                  ...    0    0    0     0     0    0    0    0    0    0  
1                  ...    0    0    0     0     0    0    0    0    0    0  
2                  ...    0    0    0     0     0    0    0    0    0    0  
3                  ...    0    0    0     0     0    0    0    0    0    0  
4                  ...    0    0    0     0     0    0    0    0    0    0  
5                  ...    0    0    0     0     0    0    0    0    0    0  
6                  ...    0    0    0     0     0    0    0    0    0    0  
7                  ...    0    0    0     0     0    0    0    0    0    0  
8                  ...    0    0    0     0     0    0    0    0    0    0  
9                  ...    0    0    0     0     0    0    0    0    0    0  
10                 ...    0    0    0     0     0    0    0    0    0    0  
11                 ...    0    0    0     0     0    0    0    0    0    0  
12                 ...    0    0    0     0     0    0    0    0    0    0  
13                 ...  388    0    0     0     0    0    0    0    0    0  
14                 ...    0  140    0     0     0    0    0    0    0    0  
15                 ...    0    0  642     0     0    0    0    0    0    0  
16                 ...    0    0    0  3720     0    0    0    0    0    0  
17                 ...    0    0    0     0  4115    0    0    0    0    0  
18                 ...    0    0    0     0     1  374    0    0    0    0  
19                 ...    0    0    0     0     1    0  374    0    0    0  
20                 ...    0    0    0     0     0    0    0  374    0    1  
21                 ...    0    0    0     0     0    0    0    0  374    1  
22                 ...    0    0    0     0     0    0    0    0    0  134  

[23 rows x 23 columns]